FitFocus/Controllers/AdminBlogPostsController.cs
using FitFocus.Models.Domain;
using FitFocus.Models.ViewModels;
using FitFocus.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FitFocus.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminBlogPostsController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly IBlogPostRepository blogPostRepository;

        public AdminBlogPostsController(ITagRepository tagRepository, IBlogPostRepository blogPostRepository)
        {
            this.tagRepository = tagRepository;
            this.blogPostRepository = blogPostRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            // Get tags from repository
            var tags = await tagRepository.GetAllAsync();

            var model = new AddBlogPostRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
            };

           return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
        {
            // Map view model to domain model
            var blogPost = new BlogPost
            {
                Heading = addBlogPostRequest.Heading,
                PageTitle = addBlogPostRequest.PageTitle,
                Content = addBlogPostRequest.Content,
                ShortDescription = addBlogPostRequest.ShortDescription,
                FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                Visible = addBlogPostRequest.Visible,
            };

            // Map tags from selected tags
            var selectedTags = new List<Tag>();
            foreach (var selectedTagId in addBlogPostRequest.SelectedTags)
            {
                var selectedTagAsGuid = Guid.Parse(selectedTagId);
                var existingTag = await tagRepository.GetAsync(selectedTagAsGuid);

                if (existingTag != null)
                {
                    selectedTags.Add(existingTag);
                }
            }
            // Mapping tags back to domain model
            blogPost.Tags = selectedTags;

            await blogPostRepository.AddAsync(blogPost);

            return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            // Call repository
            var blogPosts = await blogPostRepository.GetAllAsync();
            

            return View(blogPosts);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            // Retrieve result from repository
            var blogPost = await blogPostRepository.GetAsync(id);
            var tagsDomainModel = await tagRepository.GetAllAsync();

            if (blogPost != null)
            {
                // Map domain model into view model
                var model = new EditBlogPostRequest
                {
                    Id = blogPost.Id,
                    Heading = blogPost.Heading,
                    PageTitle = blogPost.PageTitle,
                    Content = blogPost.Content,
                    Author = blogPost.Author,
                    FeaturedImageUrl = blogPost.FeaturedImageUrl,
                    UrlHandle = blogPost.UrlHandle,
                    ShortDescription = blogPost.ShortDescription,
                    PublishedDate = blogPost.PublishedDate,
                    Visible = blogPost.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name, Value = x.Id.ToString()
                    }),
                    SelectedTags = blogPost.Tags.Select(x => x.Id.ToString()).ToArray()
                };

                return View(model);
            }

            // Pass data to view
            return View(null);
        }

        public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {
            // Map view model back to domain model
            var blogPostDomainModel = new BlogPost
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                PageTitle = editBlogPostRequest.PageTitle,
                Author = editBlogPostRequest.Author,
                Content = editBlogPostRequest.Content,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,  
                PublishedDate = editBlogPostRequest.PublishedDate,
                UrlHandle = editBlogPostRequest.UrlHandle,
                Visible = editBlogPostRequest.Visible,
            };

            // Map tags into domain model
            var selectedTages = new List<Tag>();
            foreach(var selectedTag in editBlogPostRequest.SelectedTags) 
            {
                if (Guid.TryParse(selectedTag, out var tag))
                {
                    var  foundTag = await tagRepository.GetAsync(tag);

                    if (foundTag != null) 
                    {
                        selectedTages.Add(foundTag);
                    }
                }
            }

            blogPostDomainModel.Tags = selectedTages;

            // Submit info to respository
            var updatedBlog = await blogPostRepository.UpdateAsync(blogPostDomainModel);

            if (updatedBlog != null) 
            {
                // show success
                return RedirectToAction("Edit");
            }
            // Redirect to get method
            return RedirectToAction("Edit");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditBlogPostRequest editBlogPostRequest)
        {
            // Talk to repository to delete blog post and tags
            var deletedBlogPost = await blogPostRepository.DeleteAsync(editBlogPostRequest.Id);

            if (deletedBlogPost != null)
            {
                return RedirectToAction("List");
            }

            return RedirectToAction("Edit", new { id = editBlogPostRequest.Id });

            // Display response
        }
    }

}

FitFocus/Controllers/AdminTagsController.cs
using FitFocus.Data;
using FitFocus.Models.Domain;
using FitFocus.Models.ViewModels;
using FitFocus.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Metadata.Ecma335;

namespace FitFocus.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminTagsController : Controller
    {
        private readonly ITagRepository tagRepository;

        public AdminTagsController(ITagRepository tagRepository)
        {
            this.tagRepository = tagRepository;
        }


        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }


        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest) 
        {
            ValidateTagRequest(addTagRequest);

            if (ModelState.IsValid == false)
            {
                return View();
            }
            //Mapping AddTagRequest to Tag Domain Model
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            };

            await tagRepository.AddAsync(tag);

            return RedirectToAction("List");
        }


        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List()
        {
            // Use Db Context to read tags
            var tags = await tagRepository.GetAllAsync();


            return View(tags);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var tag = await tagRepository.GetAsync(id);

            if (tag != null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName
                };

                return View(editTagRequest);
            }


            return View(null);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName
            };

            var updatedTag = await tagRepository.UpdateAsync(tag);

            if (updatedTag != null)
            {
                // show success
            }
            else
            {
                // show failed
            }

            // show failed notification
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }


        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest) 
        {
            var deletedTag = await tagRepository.DeleteAsync(editTagRequest.Id);

            if(deletedTag != null)
            {
                // show success
                return RedirectToAction("List");
            }

            // show error notification
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }

        private void ValidateTagRequest(AddTagRequest request)
        {
            if (request.Name != null && request.DisplayName != null)
            {
                if (request.Name == request.DisplayName)
                {
                    ModelState.AddModelError("DisplayName", "Name cannot be the same as DisplayName");
                }
               
            }
        }
    }
}

FitFocus/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FitFocus.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="icon" href="@Url.Content("/images/logo-fav.png")" />
    <link rel="icon" type="image/png" sizes="16x16" href="/images/logo-fav.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/8a2619a42b.js" crossorigin="anonymous"></script>
    <style>
        .search-btn {
            background-color: #f0f0f0;
        }

        .btn-no-border {
            box-shadow: none !important;
            outline: none !important;
        }

        .logo {
            width: 11em;
            height: auto;
        }

        .navbar {
            padding: 0.1em 0;
        }

        .offcanvas-header {
            justify-content: flex-end;
        }
    </style>
</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FitFocus</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@

        <nav class="navbar navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <img src="/images/white_logo.png" alt="Logo" class="img-fluid d-inline-block align-text-top logo">
                </a>
                <button class="navbar-toggler border-dark btn-no-border" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                    <div class="offcanvas-header bg-dark">
                        @* <h5 class="offcanvas-title text-light" id="offcanvasDarkNavbarLabel">Dark offcanvas</h5> *@
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body bg-dark">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">

                                @if (signInManager.IsSignedIn(User))
                                {
                                    <div class="me-3 text-light">
                                        Welcome,&nbsp;@User?.Identity?.Name
                                    </div>

                                    <a class="btn btn-login me-3 text-light"
                                       asp-area=""
                                       asp-controller="Account"
                                       asp-action="Logout">
                                        Logout
                                    </a>
                                }
                                else
                                {
                                    <a class="btn btn-login me-3 text-light"
                                       asp-area=""
                                       asp-controller="Account"
                                       asp-action="Login">
                                        Login
                                    </a>

                                    <a class="btn btn-login me-3 text-light"
                                       asp-area=""
                                       asp-controller="Account"
                                       asp-action="Register">
                                        Join
                                    </a>

                                    <a class="btn btn-login me-3 text-light"
                                       asp-area=""
                                       asp-controller="Home"
                                       asp-action="Contact">
                                        Contact
                                    </a>
                                }

                            @if (User.IsInRole("Admin") && signInManager.IsSignedIn(User))
                            {
                                <li class="nav-item dropdown my-sm-0">
                                    <a class="nav-link dropdown-toggle text-light btn-login admin-drop" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Admin
                                    </a>
                                    <ul class="dropdown-menu bg-secondary bg-gradient hover-light">
                                        <li>
                                            <a class="dropdown-item text-dark hover-light btn-login"
                                               asp-area=""
                                               asp-controller="AdminBlogPosts"
                                               asp-action="Add">
                                                Add Blog Post&nbsp;&nbsp;&#9734;
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item text-dark hover-light btn-login"
                                               asp-area=""
                                               asp-controller="AdminBlogPosts"
                                               asp-action="List">
                                                View/Edit Blog Posts
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item text-dark hover-light btn-login"
                                               asp-area=""
                                               asp-controller="AdminTags"
                                               asp-action="Add">
                                                Add New Tag
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item text-dark hover-light btn-login"
                                               asp-area=""
                                               asp-controller="AdminTags"
                                               asp-action="List">
                                                View Tags
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item text-dark hover-light btn-login"
                                               asp-area=""
                                               asp-controller="AdminUsers"
                                               asp-action="List">
                                                View Users
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            }
                        </ul>
                        @* <form class="d-flex mt-3" role="search">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn search-btn" type="submit">Search</button> 
                        </form> *@
                    </div>
                </div>
            </div>
        </nav>

    </header>
    <div>
        <main role="main" class="pb-3" style="background: #899499">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2023 - Fit Focused Health <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>